import 'all_keys.dart';

Map<String, String> ar = {
  tLogin: "تسجيل الدخول",
  tCreateANewAccount: "انشاء حساب جديد",
  tCreateNewAccount: "أنشئ حساب جديد",
  tWelcomeLine: "أهلا بك\n اكتشف حلمك الآن",
  tPhone: 'رقم الهاتف',
  tWrite: "إكتب",
  tPassword: "كلمة المرور",
  tForgotYourPassword: "هل نسيت كلمة السر؟",
  tYouDontHaveAnAccount: "ليس لديك حساب ؟",
  tSend: "إرسال",
  tForgetScreenLine:
      "لا تقلق، ما عليك سوي كتابة رقم هاتفك وسنرسل لك رمز التحقق",
  tOrBy: "او من خلال",
  tCodeVerification: "التحقق من الرمز",
  tOtpScreenLine: "ادخل الرمز الذي تم ارساله الي رقم هاتفك",
  tEditPhoneNumber: "تعديل الرقم",
  tResendMsg: "إعادة ارسال الرمز",
  tConfirmPassword: "تاكيد كلمة السر",
  tCrateNewPasswordScreenLine: "أكتب كلمة المرور الجديدة لتسجيل الدخول",
  tCrateNewPassword: "انشاء كلمة مرور جديدة",
  tChoose: "إختر",
  tAffiliateType: "نوع الافيليت",
  tNext: "التالى",
  tGovernorate: "المحافظة",
  tCity: "المدينة",
  tProductPromotionMethod: "طريقة ترويجك للمنتجات",
  tDateOfBirth: "تاريخ الميلاد",
  tAddress: "العنوان",
  tYourWebsite: "موقعك الشخصي",
  tIDontHaveAPersonalWebsite: "لا يوجد لدي موقع شخصي",
  tIAgreeToAffiliateProgram: "اوافق على برنامج المسوق بالعمولة الخاص بـ ",
  tTermsAndConditions: "الشروط والأحكام",
  tName: "الإسم",
  tFullName: "الإسم بالكامل",
  tCancel: "إلغاء",
  tYourDataHasBeenSuccessfullyModified: "تم تعديل بياناتك بنجاح",
  tBackToMain: "عودة إلى الصفحة الرئيسية",
  tPasswordChangedSuccessfully: "تم تغيير كلمة المرور بنجاح",
  tAreYouSureYouWantToLogout: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  tSignOut: "تسجيل الخروج",
  tSuccessOperation: "تمت العمليه بنجاح",
  tGoMainPage: "الذهاب الي الرئيسيه",
  tSomethingWentWrong: 'شيء ما حدث بشكل خاطئ',
  tInternalServerError: 'خطأ في السبرفر',
  tBadRequest: 'خطأ في الطلب',
  tRequestToAPIServerWasCancelled: 'تم إلغاء الطلب إلى خادم API',
  tConnectionTimeoutWithAPIServer: 'برجاء التحقق من الانترنت',
  tConnectionToAPIServerFailedDueToInternetConnection:
      'فشل الاتصال بالسيرفر بسبب الاتصال بالإنترنت',
  tReceiveTimeoutInConnectionWithAPIServer: 'برجاء التحقق من الانترنت',
  tSendTimeoutInConnectionWithAPIServer: 'برجاء التحقق من الانترنت',
  tResendCode: 'إعادة ارسال الرمز',
  tFixedCommission: "عمولة ثابتة",
  tFreeCommission: "عمولة حره",
  tWeb: 'موقع إلكترونى',
  tFacebook: 'فيس بوك',
  tTwitter: 'تويتر',
  tInstagram: 'إنستجرام',
  tPinIsIncorrect: 'الكود غير صحيح',
  tMustHaveValue: 'يجب أن يكون لها قيمة',
  tWrongNumber: 'رقم غير صحيح',
  tWrongConfirmedPassword: 'كلمة مرور مؤكدة خاطئة',
  tYouMustChooseTheProvinceFirst: "لابد من إختيار المحافظة أولا",
  tWrongEmail: "بريد الكترونى خاطئي",
  tEmail: "بريد الكترونى",
  tWrongWebSite: 'موقع خاطئ',
  tWritePassword: 'من  فضلك  ادخل  كلمه السر',
  tWriteName: 'من فضلك ادخل الاسم',
  tWritePhone: ' من فضلك  ادخل رقم الهاتف ',
  tShowAll: 'عرض الكل ',
  tAddToCart: 'اضف الي عربة التسوق',
  tPrice: 'السعر',
  tCommission: 'العمولة',
  tWriteDate: "اختر تاريخ ميلادك",
  tYouMustChoose: "بحاجة إلى الاختيار",
  tPleaseWrite: 'أكتب رجاءا',
  tGoTo: 'الذهاب الى',
  tNeedToSignUpFirst: 'بحاجة للتسجيل أولا',
  tMustChoose: ' من فضلك إختر',
  tMustWrite: ' من فضلك إكتب',
  tNotification: 'الاشعارات',
  tConfirm: "تاكيد",
  tSave: "حفظ",

  tFavorite: 'المفضلة',
  tExplanationOfTheSystem: "شرح النظام",
  tHome: "الرئيسية",
  tReports: "التقارير",
  tMyOrders: "طلباتي",
  tProducts: "المنتجات",
  tBrands: "الماركات",
  tCatagories: "الاقسام",
  tDisc: "الوصف",
  tSizes: "المقاسات",
  tSize: "المقاس",
  tColors: "الالوان",
  tColor: "اللون",
  tCount: "العدد",
  tNoProducts: "لا يوجد منتجات",
  tMyTeam: "فريقي",
  tModerators: "المدريتورز",
  tTechSystem: "شرح السيستم",
  tContactSupport: "تواصل مع الدعم",
  tLanguage: "اللغة",
  tThePayment: "الدفع",
  tStatistics: "الاحصائيات",
  tTheCalculations: "الحسابات",
  tCopyRegisterLink: "نسخ رابط التسجيل",
  tDelete: "حذف",
  tAffiliateCode: "افلييت كود",
  tMembers: "أعضاء",
  tOrders: "طلبات",
  tTeamLeader: "تيم ليدر",
  tYourTeam: "فريقك",

  tPaymentMethod: "طريقة الدفع",
  tSupportCenter: 'مركز الدعم',
  tAvailableNow: 'متاح الآن',
  tNoNotifications: 'لايوجد اشعارات لعرضها',
  tYouHave: "لديك",
  tNewNotificationsToday: "اشعارات جديدة اليوم",
  tAllProducts: "كل المنتجات",
  tTheCategory: "الفئة",
  tTheMarks: "الماركة",
  tTheCommission: "العمولة",
  tThePrice: "السعر",
  tAddOrder: 'إضافة طلب',
  tConfirmOrder: 'تأكيد الطلب',
  tEndCheckout: 'إتمام الشراء',
  tDetailedAddress: "العنوان التفصيلي",
  tAnotherPhoneNumber: "رقم هاتف اخر",
  tOrderDetails: "تفاصيل الاوردر",
  tFacebookPage: "صفحة الفيسبوك",
  tTheMarketing: "التسويق",
  tTheClient: "العميل",
  tNotes: "ملاحظات",
  tLink: "رابط",
  tAName: "إسم",
  tAddOrders: "إضافه منتجات",
  tSearchForProducts: "إبحث عن المنتجات",
  tTheShipping: "الشحن",
  tNow: 'الآن',
  tLaterOn: 'في وقت لاحق',
  tTotalPrice: 'اجمالي السعر',
  tTotalCommission: 'اجمالي العمولة',
  tPriceOfTheShipping: 'سعر الشحن',
  tReceivingDate: 'موعد الاستلام',
  tEditPrice: ' تعديل السعر ',
  tTheQuantity: 'الكمية',
  tTheDataOfClient: 'بيانات العميل',
  tEgyptPound: 'جنيه',
  tTheOrders: "الطلبات",
  tTheCurrent: 'الحالية',
  tThePast: 'السابقة',
  tNoOrder : "لا يوجد طلب حتى الآن",


     tOrderNo: "طلبية رقم",
  tOrderCode: "كود الاوردر",
  tClientName: "اسم العميل",
  tTransData: "تاريخ التحويل",
  tSalaryAmount: "المبلغ",
  tStatus: "الحالة",
  tOrderState:"حاله الطلب",
  tNeedToSelectProductFirst : "تحتاج إلى تحديد المنتجات أولاً",
  tDoYouWantTo:"هل تريد ",







   tShoppingCart: "عربة التسوق",
  tAdd: "إضافه",
  tCheckout: "إتمام الشراء",
  tAddModerator: "إضافه مودريتور",
  tCheckoutData: "تاريخ الطلب",
  tShippingDate: "تاريخ الشحن",
  tSelect: "تحديد",
  tEmptyCart:"سلة فارغه",



  tCommissionTransferRequest : 'طلب تحويل العمولة'


};
