import 'package:get/get.dart';

import 'all_keys.dart';

Map<String, String> en = {
  tLogin: "login",
  tCreateANewAccount: "create A New Account",
  tCreateNewAccount: "create A New Account",
  tWelcomeLine: "Welcome\n Find out your dream now",
  tPhone: 'Phone Number',
  tWrite: "Write",
  tPassword: "password",
  tForgotYourPassword: "Forgot your password?",
  tYouDontHaveAnAccount: "You Don't Have An Account",
  tSend: "Send",
  tForgetScreenLine:
      "Don't worry, just type in your phone number and we'll send you a verification code.",
  tOrBy: "OR",
  tCodeVerification: "Code Verification",
  tOtpScreenLine: "Enter the code that was sent to your phone number.",
  tEditPhoneNumber: "Edit Phone Number",
  tResendMsg: "Resend Code",
  tConfirmPassword: "Confirm Password",
  tCrateNewPasswordScreenLine: "Type the new password to log in",
  tCrateNewPassword: "Crate New Password",
  tChoose: "Choose",
  tAffiliateType: "AffiliateType",
  tNext: "Next",
  tGovernorate: "Governorate",
  tCity: "City",
  tProductPromotionMethod: "Product promotion method",
  tDateOfBirth: "Date of Birth",
  tAddress: "Address",
  tYourWebsite: "Your Website",
  tIDontHaveAPersonalWebsite: "I don't have a personal website",
  tIAgreeToAffiliateProgram: "I agree to .'s Affiliate Program",
  tTermsAndConditions: "Terms and Conditions",
  tName: "Name",
  tFullName: "Full Name",
  tCancel: 'cancel',
  tYourDataHasBeenSuccessfullyModified:
      'Your data has been successfully modified',
  tBackToMain: 'back to main',
  tPasswordChangedSuccessfully: 'Password changed successfully',
  tAreYouSureYouWantToLogout: 'Are you sure you want to log out?',
  tSignOut: 'sign out',
  tSuccessOperation: 'operation accomplished successfully',
  tGoMainPage: "GoMainPage",
  tSomethingWentWrong: 'Oops something went wrong',
  tInternalServerError: 'Internal server error',
  tBadRequest: 'Bad request',
  tRequestToAPIServerWasCancelled: 'Request to API server was cancelled',
  tConnectionTimeoutWithAPIServer: 'Connection timeout with API server',
  tConnectionToAPIServerFailedDueToInternetConnection:
      'Connection to API server failed due to internet connection',
  tReceiveTimeoutInConnectionWithAPIServer:
      'Receive timeout in connection with API server',
  tSendTimeoutInConnectionWithAPIServer:
      'Send timeout in connection with API server',
  tResendCode: 'Resend Code',
  tFixedCommission: "fixed commission",
  tFreeCommission: "Free Commission",
  tWeb: 'WebSite',
  tFacebook: 'Facebook',
  tTwitter: 'Twitter',
  tInstagram: 'Instagram',
  tPinIsIncorrect: 'Pin is incorrect',
  tMustHaveValue: 'must have value',
  tWrongNumber: 'wrong number',
  tWrongConfirmedPassword: 'wrong confirmed password',
  tYouMustChooseTheProvinceFirst:
      "You Must Choose The ${tGovernorate.tr} First",
  tWrongEmail: "Wrong Email",
  tEmail: "Email",
  tWrongWebSite: "Wrong Web-Site",
  tWritePassword: 'Please enter your password',
  tWriteName: 'please Write Name',
  tWritePhone: 'please WritePhone',
  tShowAll: 'Show All',
  tAddToCart: 'Add To Cart',
  tPrice: 'price',
  tCommission: 'Commission',
  tWriteDate: 'choose your Birth Date',
  tYouMustChoose: 'need to choose',
  tPleaseWrite: 'please write',
  tGoTo: 'Go To',
  tNeedToSignUpFirst: 'Need To Sign Up First',
  tMustChoose: 'You Must Choose',
  tMustWrite: 'You Must Write',
  tNotification: 'Notifications',
  tConfirm: "Confirm",
  tSave: "Save",

  tFavorite: 'Favorite',
  tExplanationOfTheSystem: "Explanation of the system",
  tHome: "Home",
  tReports: "Reports",
  tMyOrders: "MyOrders",
  tProducts: "Products",
  tBrands: "Brands",
  tCatagories: "Catagories",
  tDisc: "Description",
  tSizes: "Sizes",
  tSize: "Size",
  tColors: "Colors",
  tColor: "Color",
  tCount: "Count",
  tNoProducts: "No Products",
  tMyTeam: "My Team",
  tModerators: "Moderators",
  tTechSystem: "Tech System",
  tContactSupport: "Contact Support",
  tLanguage: "Language",
  tThePayment: "Payment",
  tStatistics: "Statistics",
  tTheCalculations: "Calculations",
  tCopyRegisterLink: "Copy Register Link",
  tDelete: "Delete",
  tAffiliateCode: "Affiliate Code",
  tMembers: "Members",
  tOrders: "Orders",
  tTeamLeader: "TeamLeader",
  tYourTeam: "Your Team",

  tPaymentMethod: "Payment Method",
  tSupportCenter: 'Support Center',
  tAvailableNow: 'Available Now',
  tNoNotifications: 'No Notifications Found',
  tYouHave: "you have",
  tNewNotificationsToday: "New Notifications Today",
  tAllProducts: "All Products",
  tTheCategory: "The Category",
  tTheMarks: "The Marks",
  tTheCommission: "The Commission",
  tThePrice: "The Price",
  tAddOrder: 'Add Order',
  tConfirmOrder: 'Confirm Order',
  tEndCheckout: 'End Checkout',
  tOrderDetails: "Order Details",
  tAnotherPhoneNumber: "Another Phone Number",
  tDetailedAddress: "Detailed Address",
  tFacebookPage: "Facebook Page",
  tTheMarketing: "For Marketing",
  tNotes: "Notes",
  tTheClient: " TheClient",
  tLink: "Link",
  tAName: "A Name",
  tAddOrders: "Add Orders",
  tSearchForProducts: "Search For Products",
  tTheShipping: "The Shipping",
  tNow: 'Now',
  tLaterOn: 'Later On',
  tTotalPrice: 'Total Price',
  tTotalCommission: 'Total Commission',
  tPriceOfTheShipping: 'Price Of The Shipping',
  tReceivingDate: 'Receiving Date',
  tEditPrice: 'Edit Price',
  tTheQuantity: 'TheQuantity',
  tTheDataOfClient: 'Data Of Client',
  tEgyptPound: 'Egypt Pound',
  tTheOrders:"My Orders",

   tTheCurrent : 'The Current',
 tThePast : 'The Past',
  tNoOrder : "No Order Yet",

   tOrderNo : "Order No",
 tOrderCode : "Order Code",
 tClientName : "Client Name",
 tTransData : "Trans Data",
 tSalaryAmount : "Salary Amount",
 tStatus : "Status",
 tOrderState: "Order State",
  tNeedToSelectProductFirst : "need to select product first",
  tDoYouWantTo:"do you want to",





   tShoppingCart : "Shopping Cart",
 tAdd : "Add",
 tCheckout : "Checkout",
 tAddModerator : "Add Moderator",
 tCheckoutData : "Checkout Date",
 tShippingDate : "Shipping Date",
 tSelect : "Select",


 tEmptyCart:"Empty Cart",



  tCommissionTransferRequest : 'Commission transfer request'
};
